#if !defined(AFX_CLOCKSERIES1_H__6B50895A_4DBF_41CE_B7C3_F9EB4A3E1A1E__INCLUDED_)
#define AFX_CLOCKSERIES1_H__6B50895A_4DBF_41CE_B7C3_F9EB4A3E1A1E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;
class CPointer;
class CValueList;
class CCircleLabels;
class CBrush1;

/////////////////////////////////////////////////////////////////////////////
// CClockSeries wrapper class

class CClockSeries : public COleDispatchDriver
{
public:
	CClockSeries() {}		// Calls COleDispatchDriver default constructor
	CClockSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CClockSeries(const CClockSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetXRadius();
	void SetXRadius(long nNewValue);
	long GetYRadius();
	void SetYRadius(long nNewValue);
	long GetXCenter();
	long GetYCenter();
	long GetCircleWidth();
	long GetCircleHeight();
	unsigned long GetCircleBackColor();
	void SetCircleBackColor(unsigned long newValue);
	BOOL GetCircled();
	void SetCircled(BOOL bNewValue);
	long GetRotationAngle();
	void SetRotationAngle(long nNewValue);
	// method 'AngleToPoint' not emitted because of invalid return type or parameter type
	double PointToAngle(long XCoord, long YCoord);
	double GetAngleIncrement();
	void SetAngleIncrement(double newValue);
	BOOL GetCloseCircle();
	void SetCloseCircle(BOOL bNewValue);
	CPen1 GetPen();
	CPointer GetPointer();
	double GetRadiusIncrement();
	void SetRadiusIncrement(double newValue);
	CValueList GetAngleValues();
	CValueList GetRadiusValues();
	void DrawRing(double Value, long Z);
	CPen1 GetCirclePen();
	CCircleLabels GetCircleLabels();
	CBrush1 GetBrush();
	void LoadBackImage(LPCTSTR FileName);
	void ClearBackImage();
	BOOL GetClockWiseLabels();
	void SetClockWiseLabels(BOOL bNewValue);
	BOOL GetCircleLabelsInside();
	void SetCircleLabelsInside(BOOL bNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	BOOL GetRomanNumbers();
	void SetRomanNumbers(BOOL bNewValue);
	CPen1 GetPenHours();
	CPen1 GetPenMinutes();
	CPen1 GetPenSeconds();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CLOCKSERIES1_H__6B50895A_4DBF_41CE_B7C3_F9EB4A3E1A1E__INCLUDED_)
