#if !defined(AFX_HISTOGRAMSERIES1_H__BDE9B390_880C_4553_83A2_5A44D486A117__INCLUDED_)
#define AFX_HISTOGRAMSERIES1_H__BDE9B390_880C_4553_83A2_5A44D486A117__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;
class CBrush1;

/////////////////////////////////////////////////////////////////////////////
// CHistogramSeries wrapper class

class CHistogramSeries : public COleDispatchDriver
{
public:
	CHistogramSeries() {}		// Calls COleDispatchDriver default constructor
	CHistogramSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHistogramSeries(const CHistogramSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPen1 GetLinesPen();
	long GetTransparency();
	void SetTransparency(long nNewValue);
	CPen1 GetLinePen();
	CBrush1 GetBrush();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HISTOGRAMSERIES1_H__BDE9B390_880C_4553_83A2_5A44D486A117__INCLUDED_)
