//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 轨道清洁检测车监控系统.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MY_DIALOG                   102
#define IDD_DIALOG_MAIN                 102
#define IDR_MAINFRAME                   128
#define IDR_DIALOG_MENU                 129
#define IDD_DIALOG_WIND_PRE             131
#define IDD_DIALOG_OIL_TEM              133
#define IDD_DIALOG_OUTSIDE_TEM          134
#define IDD_DIALOG_CLEAN_WATER_BOX      135
#define IDD_DIALOG_DIRTY_WATER_BOX      136
#define IDD_CLEAN_WATER_CHART           141
#define IDD_DIALOG_INSIDE_TEMP          143
#define IDD_DIALOG_WATER_TEMP           144
#define IDD_DIALOG_VOLT                 145
#define IDD_DIRTY_WATER_CHART           154
#define IDD_WATER_TEMP_CHART            155
#define IDC_EDIT_WIND_PRE               1005
#define IDC_BUTTON_WINDPRE              1007
#define IDC_BUTTON_OILPRE               1008
#define IDC_ALRAM_TEXT                  1009
#define IDC_EDIT_OUTSIDE_TEM            1010
#define IDC_EDIT_OIL_TEM                1011
#define IDC_BUTTON_OIL_TEM              1012
#define IDC_BUTTON_WATER_TEMP           1012
#define IDC_BUTTON_OUTSIDE_TEM          1013
#define IDC_BUTTON_CLEAN_WATER_BOX      1014
#define IDC_BUTTON_INSIDE_TEMP          1015
#define IDC_BUTTON_DIRTY_WATER_BOX      1016
#define IDC_EDIT_DIRTY_WATER_BOX        1017
#define IDC_EDIT_CLEAN_WATER_BOX        1018
#define IDC_WIND_PRE                    1024
#define IDC_OIL_TEMP                    1026
#define IDC_WATER_TEMP                  1026
#define IDC_OUTSIDE_TEMP                1027
#define IDC_CLEAN_WATER                 1028
#define IDC_DIRTY_WATER                 1029
#define IDC_INSIDE_TEMP                 1030
#define IDC_EDIT1                       1031
#define IDC_EDIT_FRONT_LEFT             1031
#define IDC_TITLE                       1031
#define IDC_EDIT2                       1032
#define IDC_EDIT_TIME                   1032
#define IDC_EDIT3                       1033
#define IDC_RANGE_CHANGE                1033
#define IDC_EDIT4                       1034
#define IDC_ALARM_CHANGE                1034
#define IDC_VOLT                        1035
#define IDC_EDIT_WATER                  1035
#define IDC_BUTTON1                     1036
#define IDC_BUTTON_LOOKBACK             1036
#define IDC_BUTTON_SHOW                 1036
#define IDC_BUTTON2                     1037
#define IDC_BUTTON_CURRENT_RANGE        1037
#define IDC_BUTTON_SHOW_SELECT          1037
#define IDC_BUTTON3                     1038
#define IDC_BUTTON_ALRAM                1038
#define IDC_EDIT_OUTSIDE                1038
#define IDC_EDIT_INSIDE                 1039
#define IDC_BUTTON4                     1040
#define IDC_BUTTON_EDIT_RANGE           1040
#define IDC_BUTTON5                     1041
#define IDC_BUTTON_EDIT_ALRAM           1041
#define IDC_BUTTON6                     1042
#define IDC_BUTTON_CONFIRM              1042
#define IDC_BUTTON7                     1043
#define IDC_BUTTON_OUTPUT_TABLE         1043
#define IDC_GRID_CLEAN_WATER            1044
#define IDC_FRONT_WIND_TEXT             1045
#define IDC_BACK_WIND_TEXT1             1046
#define IDC_BACK_WIND_TEXT2             1047
#define IDC_LOW_WATER_PRE               1049
#define IDC_HIGH_WATER_PRE              1050
#define IDC_BUTTON_VOLT                 1051
#define IDC_LONGITUDE_TEXT              1052
#define IDC_LATITUDE_TEXT               1053
#define IDC_CLEAN_WATER_TEXT            1054
#define IDC_DIRTY_WATER_TEXT            1055
#define IDC_EDIT_FRONT_RIGHT            1056
#define IDC_EDIT_BACK_LEFT              1057
#define IDC_EDIT_BACK_RIGHT             1058
#define IDC_BUTTON_DELETE               1062
#define IDC_INSIDE_TEMP_MAIN            1067
#define IDC_TCHART2                     1068
#define IDC_WATER_MAIN                  1070
#define IDC_INSIDE_MAIN                 1071
#define IDC_GRID_DIRTY_WATER            1071
#define IDC_OUTSIDE_MAIN                1072
#define IDC_EDIT_ENGINE                 1072
#define IDC_GRID_TEMP                   1073
#define IDM_LOOKBACK                    32771
#define IDM_CURRANGE                    32772
#define IDM_ALRAMHIS                    32773
#define IDM_EDITRANGE                   32774
#define IDM_EDITALRAM                   32775
#define IDM_PRINTTABLE                  32776
#define IDM_CALMAXORMIN                 32777
#define IDM_CALAVER                     32778
#define IDM_ABOUT                       32779
#define IDM_CLEAN_WATER                 32780
#define IDM_DIRTY_WATER                 32781
#define IDM_OIL_TEMP                    32782
#define IDM_WATER_TEMP                  32782
#define IDM_OUTSIDE_TEMP                32783
#define IDM_WIND_PRE                    32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
