// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "tools1.h"

// Dispatch interfaces referenced by this interface
#include "CursorTool1.h"
#include "DragMarksTool1.h"
#include "AxisArrowTool1.h"
#include "DrawLineTool1.h"
#include "nearesttool1.h"
#include "ColorBandTool1.h"
#include "ColorLineTool1.h"
#include "rotatetool1.h"
#include "MarksTipTool1.h"
#include "ChartImageTool1.h"
#include "annotationtool1.h"
#include "PageNumTool1.h"


/////////////////////////////////////////////////////////////////////////////
// CTools properties

/////////////////////////////////////////////////////////////////////////////
// CTools operations

CCursorTool CTools::GetAsTeeCursor()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CCursorTool(pDispatch);
}

CDragMarksTool CTools::GetAsDragMarks()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CDragMarksTool(pDispatch);
}

CAxisArrowTool CTools::GetAsAxisArrow()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CAxisArrowTool(pDispatch);
}

CDrawLineTool CTools::GetAsDrawLine()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CDrawLineTool(pDispatch);
}

CNearestTool CTools::GetAsNearest()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CNearestTool(pDispatch);
}

CColorBandTool CTools::GetAsColorband()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CColorBandTool(pDispatch);
}

CColorLineTool CTools::GetAsColorLine()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x7, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CColorLineTool(pDispatch);
}

CRotateTool CTools::GetAsRotate()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CRotateTool(pDispatch);
}

CMarksTipTool CTools::GetAsMarksTip()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CMarksTipTool(pDispatch);
}

CChartImageTool CTools::GetAsChartImage()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xa, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CChartImageTool(pDispatch);
}

CAnnotationTool CTools::GetAsAnnotation()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xb, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CAnnotationTool(pDispatch);
}

CPageNumTool CTools::GetAsPageNum()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xc, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CPageNumTool(pDispatch);
}

BOOL CTools::GetActive()
{
	BOOL result;
	InvokeHelper(0xd, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CTools::SetActive(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xd, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CString CTools::GetDescription()
{
	CString result;
	InvokeHelper(0xe, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CTools::GetToolType()
{
	long result;
	InvokeHelper(0xf, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}
